/**
 * Constitution PDF Service
 *
 * English PDF  : "constitution_english.pdf"
 *   Format: "<number>. Title.—Body text" per article (diglot edition)
 *   Detection: lines matching /^\d+[A-Z]?\.\s+\S+.*[—–-]/ mark article starts
 *
 * Tamil PDF    : "constitution_tamil.pdf"
 *   NOTE: This PDF uses TSCII/legacy Tamil font encoding, so pdf-parse returns
 *   visually garbled characters rather than Unicode Tamil. The service stores
 *   the raw extracted text per chunk anyway and marks it `encoding: 'tscii'`
 *   so the frontend can display an appropriate notice. When a proper Unicode
 *   Tamil PDF is available, replace the file and call POST /cache/invalidate.
 *
 * Both results are cached in memory after first parse.
 */

import fs from 'fs';
import path from 'path';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const pdfParse = require('pdf-parse');
import logger from '../config/logger';

// ── Paths ─────────────────────────────────────────────────────────────────────
const DATA_DIR    = path.resolve(__dirname, '../../database/data');
const ENGLISH_PDF = path.join(DATA_DIR, 'constitution_english.pdf');
const TAMIL_PDF   = path.join(DATA_DIR, 'constitution_tamil.pdf');
// Pre-OCR'd Unicode text file (generated by ocr_tamil_pdf.py) — used when PDF is legacy-encoded
const TAMIL_TXT   = path.join(DATA_DIR, 'constitution_tamil_unicode.txt');

// ── Types ─────────────────────────────────────────────────────────────────────
export interface PdfArticle {
  article_id:   string;
  article_desc: string;
  art_no:       string;
  name:         string | null;
  source:       'pdf_english' | 'pdf_tamil';
  language:     'en' | 'ta';
  encoding?:    'unicode' | 'tscii';   // only set for Tamil
  pdfPage?:     number;               // page number in the source PDF
}

// ── In-memory cache ────────────────────────────────────────────────────────────
const cache: { en: PdfArticle[] | null; ta: PdfArticle[] | null } = {
  en: null,
  ta: null,
};

// ── Raw text extraction ────────────────────────────────────────────────────────
async function extractText(pdfPath: string): Promise<string> {
  const buf    = fs.readFileSync(pdfPath);
  const result = await pdfParse(buf);
  return (result.text as string) || '';
}

/** If a pre-OCR'd Unicode text file exists, use it instead of parsing the PDF */
function readTamilTxtIfAvailable(): string | null {
  if (fs.existsSync(TAMIL_TXT)) {
    logger.info('Tamil: using pre-OCR\u2019d Unicode text file (constitution_tamil_unicode.txt)');
    return fs.readFileSync(TAMIL_TXT, 'utf-8');
  }
  return null;
}

// ── English splitting ──────────────────────────────────────────────────────────
/**
 * The English constitution PDF (diglot edition) has this format in the body:
 *   "21. Protection of life and personal liberty.—No person shall…"
 *
 * TOC lines look like:
 *   "21. Protection of life and personal liberty."
 * (no em-dash, no body text)
 *
 * We split on lines that match  /^\d+[A-Z]?\.\s+\S.*[—–-]/  which catches
 * only the content lines (they always have the dash before the body text).
 */
function splitEnglish(text: string): PdfArticle[] {
  const lines = text.split('\n');
  const articles: PdfArticle[] = [];

  // Regex: starts with "<number[letter]>. " followed by non-whitespace and contains —/–/-
  // Only em-dash (—) marks a true content article; TOC lines use just a period
  const ARTICLE_START = /^(\d+[A-Z]?)\.\s+(.+?)[—–]/i;

  let currentNo   = '';
  let currentName = '';
  let currentPage = 1;   // track PDF page via form-feed characters
  let articlePage = 1;   // page where current article started
  let buf: string[] = [];

  const flush = () => {
    if (!currentNo || !buf.length) return;
    const body = buf.join(' ').replace(/\s{2,}/g, ' ').trim();
    if (body.length < 20) return;                // skip stub entries
    articles.push({
      article_id:   `Article ${currentNo} of Indian Constitution`,
      art_no:       currentNo,
      name:         currentName || null,
      article_desc: body,
      source:       'pdf_english',
      language:     'en',
      pdfPage:      articlePage,
    });
  };

  for (const line of lines) {
    // Form-feed (\f) signals a new page in most PDF text extractions
    if (line.includes('\f')) {
      currentPage++;
    }
    const trimmed = line.replace(/\f/g, '').trim();
    const m = trimmed.match(ARTICLE_START);

    if (m) {
      flush();
      buf         = [trimmed];
      currentNo   = m[1].toUpperCase();
      articlePage = currentPage;
      // extract title: everything before the dash
      const dashIdx = trimmed.search(/[—–-]/);
      currentName   = dashIdx > 0
        ? trimmed.slice(trimmed.indexOf('.') + 1, dashIdx).trim()
        : '';
    } else if (currentNo) {
      buf.push(trimmed);
    }
  }
  flush();

  if (articles.length < 50) {
    logger.warn(`English PDF: only ${articles.length} articles detected — falling back to chunk split`);
    return chunkFallback(text, 'en');
  }

  logger.info(`English PDF: split into ${articles.length} articles`);
  return articles;
}

// ── Tamil splitting ────────────────────────────────────────────────────────────
/**
 * The Tamil constitution PDF uses a legacy TSCII font encoding.
 * pdf-parse returns the raw byte-mapped characters (looks like garbled Latin).
 * We chunk the text into 400-word blocks and flag the encoding so the
 * frontend can show an appropriate banner rather than garbled text.
 *
 * When a proper Unicode Tamil PDF is provided, replace the file and bust
 * the cache — the unicode branch below will take over automatically.
 */
function splitTamil(text: string): PdfArticle[] {
  // Detect whether the PDF is proper Unicode Tamil (≥ 500 Tamil codepoints)
  const tamilCount = (text.match(/[\u0B80-\u0BFF]/g) || []).length;
  logger.info(`Tamil PDF: detected ${tamilCount} Tamil Unicode codepoints`);
  const isUnicode  = tamilCount > 100; // lowered from 500

  if (isUnicode) {
    // Unicode Tamil — "பிரிவு <n>", "சட்டப்பிரிவு <n>", "கட்டுரை <n>", or "<n>. Title" at line start
    const lines = text.split('\n');
    const MARKER = /^(?:(?:சட்டப்பிரிவு|பிரிவு|கட்டுரை)\s+(\d+[a-zA-Z]?)\b|(\d+[A-Z]?)\.\s+(\S.*))(\s*.*)?$/i;
    const articles: PdfArticle[] = [];
    let currentNo   = '';
    let currentName = '';
    let buf: string[] = [];

    const flush = () => {
      if (!currentNo || !buf.length) return;
      const body = buf.join(' ').replace(/\s{2,}/g, ' ').trim();
      if (body.length < 10) return;
      articles.push({
        article_id:   `பிரிவு ${currentNo}`,
        art_no:       currentNo,
        name:         currentName || null,
        article_desc: body,
        source:       'pdf_tamil',
        language:     'ta',
        encoding:     'unicode',
      });
    };

    for (const line of lines) {
      const m = line.match(MARKER);
      if (m) {
        flush();
        buf = [line.trim()];
        // Group 1,4: Tamil "பிரிவு N" + rest; Group 2,3: "N. Title" style
        currentNo   = m[1] ?? m[2] ?? '';
        currentName = (m[1] !== undefined ? (m[4] || '').trim() : (m[3] || '').trim()).replace(/^[.\-—:\s]+/, '');
      } else if (currentNo) {
        buf.push(line.trim());
      }
    }
    flush();

    if (articles.length >= 10) { // lowered from 25
      logger.info(`Tamil PDF (Unicode): split into ${articles.length} articles`);
      return articles;
    }
    logger.warn(`Fewer than 10 Tamil markers — chunk-split fallback will be used (found ${articles.length})`);
  }

  // TSCII / legacy encoding — chunk and flag
  logger.warn('Tamil PDF uses legacy TSCII encoding. Chunks stored as-is; frontend will show encoding notice.');
  return chunkFallback(text, 'ta', true);
}

// ── Chunk fallback ────────────────────────────────────────────────────────────
function chunkFallback(
  text:       string,
  lang:       'en' | 'ta',
  isTscii:    boolean = false,
): PdfArticle[] {
  const WORDS_PER_CHUNK = 500;
  const words   = text.split(/\s+/).filter(Boolean);
  const result: PdfArticle[] = [];
  let idx = 1;

  for (let i = 0; i < words.length; i += WORDS_PER_CHUNK) {
    const body = words.slice(i, i + WORDS_PER_CHUNK).join(' ');
    result.push({
      article_id:   lang === 'ta' ? `பகுதி ${idx}` : `Section ${idx}`,
      art_no:       String(idx),
      name:         lang === 'ta' ? `பகுதி ${idx}` : `Section ${idx}`,
      article_desc: isTscii
        ? `[மரபு குறியாக்கம் — Unicode Tamil PDF தேவை]\n\n${body}`
        : body,
      source:       lang === 'ta' ? 'pdf_tamil' : 'pdf_english',
      language:     lang,
      ...(isTscii ? { encoding: 'tscii' as const } : {}),
    });
    idx++;
  }
  return result;
}

// ── Loader ────────────────────────────────────────────────────────────────────
async function loadPdf(lang: 'en' | 'ta'): Promise<PdfArticle[]> {
  if (cache[lang]) return cache[lang]!;

  try {
    let text: string;

    if (lang === 'ta') {
      // Prefer pre-OCR'd Unicode text if available (fixes legacy VANAVIL encoding)
      const preOcr = readTamilTxtIfAvailable();
      if (preOcr) {
        text = preOcr;
      } else {
        if (!fs.existsSync(TAMIL_PDF)) {
          logger.warn(`Constitution PDF not found: ${TAMIL_PDF}`);
          return [];
        }
        logger.info(`Parsing constitution PDF (ta): ${path.basename(TAMIL_PDF)}`);
        text = await extractText(TAMIL_PDF);
      }
    } else {
      if (!fs.existsSync(ENGLISH_PDF)) {
        logger.warn(`Constitution PDF not found: ${ENGLISH_PDF}`);
        return [];
      }
      logger.info(`Parsing constitution PDF (en): ${path.basename(ENGLISH_PDF)}`);
      text = await extractText(ENGLISH_PDF);
    }

    const articles = lang === 'en' ? splitEnglish(text) : splitTamil(text);
    cache[lang]    = articles;
    return articles;
  } catch (err) {
    logger.error(`Failed to parse PDF (${lang}):`, err);
    return [];
  }
}

// ── Public API ─────────────────────────────────────────────────────────────────
export interface PdfArticlesResult {
  articles:    PdfArticle[];
  total:       number;
  page:        number;
  limit:       number;
  totalPages:  number;
  language:    'en' | 'ta';
  source:      'pdf';
  encoding?:   'unicode' | 'tscii';
}

export async function getConstitutionPdfArticles(
  lang:    'en' | 'ta',
  page:    number = 1,
  limit:   number = 10,
  search?: string,
): Promise<PdfArticlesResult> {
  const all = await loadPdf(lang);

  let filtered = all;
  if (search?.trim()) {
    const q = search.trim().toLowerCase();
    filtered = all.filter(
      (a) =>
        a.art_no.toLowerCase().includes(q)        ||
        (a.name || '').toLowerCase().includes(q)  ||
        a.article_desc.toLowerCase().includes(q)  ||
        a.article_id.toLowerCase().includes(q),
    );
  }

  const total      = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / limit));
  const offset     = (page - 1) * limit;
  const paged      = filtered.slice(offset, offset + limit);

  // Detect overall encoding of this batch
  const encoding = paged.some((a) => a.encoding === 'tscii') ? 'tscii' : 'unicode';

  return {
    articles:  paged,
    total,
    page,
    limit,
    totalPages,
    language:  lang,
    source:    'pdf',
    ...(lang === 'ta' ? { encoding } : {}),
  };
}

export function invalidatePdfCache(lang?: 'en' | 'ta') {
  if (lang) {
    cache[lang] = null;
    logger.info(`PDF cache invalidated for: ${lang}`);
  } else {
    cache.en = null;
    cache.ta = null;
    logger.info('PDF cache invalidated for all languages');
  }
}
